name: Build and Push Multi-Platform Docker Images on Tag Push

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get tag 
      uses: docker/metadata-action@v5
      id: meta
      with:
<<<<<<< HEAD
        images: |
          ghcr.io/${{ github.actor }}/texlive
=======
        images: ghcr.io/${{ github.repository_owner }}/texlive
>>>>>>> parent of 52af688 (認証通らん)
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        # context: ./frontend
        push: true
<<<<<<< HEAD
        tags: ${{ steps.meta.outputs.tags }} 
=======
        tags: |
          ghcr.io/${{ github.repository_owner }}/texlive:latest
          ${{ steps.meta.outputs.tags }} 
>>>>>>> parent of 52af688 (認証通らん)
        platforms: linux/amd64,linux/arm64
