name: Build and Push Multi-Platform Docker Images on Tag Push

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v2

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ghcr.io/${{ github.repository_owner }}/texlive
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        # context: ./frontend
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/texlive:latest
          ${{ steps.meta.outputs.tags }} 
        platforms: linux/amd64,linux/arm64

          
    # - name: Build and push images
    #   run: |
    #     docker buildx build \
    #       --platform linux/amd64,linux/arm64 \
    #       -t ghcr.io/songmu/riji:${{ steps.meta.outputs.tags }} .

    # - name: Publish build artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: docker-images
    #     path: .docker/images

    # - uses: docker/metadata-action@v3
    #   id: meta
    #   with:
    #     images: ghcr.io/songmu/riji
    #     tags: |
    #       type=semver,pattern={{version}}
    #       type=semver,pattern={{major}}.{{minor}}

    # - uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: songmu
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

